name: Documentation Problem
description: Report a problem with the Spacebin documentation
title: 'docs: '
labels:
  -  📖 documentation
projects: lukewhrit/2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: dropdown
    id: section
    attributes:
      label: What section of the documentation is this issue related to?
      options:
        - Self-hosting with Docker
        - Self-hosting manually
        - Environment variables
        - Using on the web
        - Using the CLI
        - API
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: checkbox
    id: pr
    attributes:
      label: Are you willing to submit a PR to resolve the problem?
      options:
        - Yes
        - No
